version: 2
updates:
  - package-ecosystem: 'pnpm'
    directory: '/'
    schedule:
      interval: 'weekly'
      time: '03:00'
    open-pull-requests-limit: 10
    assignees:
      - 'dawidrylko'
    reviewers:
      - 'dawidrylko'
    rebase-strategy: auto
    groups:
      lint:
        dependency-type: 'development'
        patterns:
          - '@eslint/*'
          - 'eslint*'
      typescript:
        dependency-type: 'development'
        patterns:
          - '@types/*'
    ignore:
      - dependency-name: 'katex'
      - dependency-name: 'react'
        update-types: ['version-update:semver-major']
      - dependency-name: 'react-dom'
        update-types: ['version-update:semver-major']
