import * as React from 'react';
import { useSiteMetadata } from '../hooks/use-site-metadata';
import { SITE_METADATA } from '../constants/site-metadata';

type SeoProps = {
  lang?: string;
  title?: string;
  description?: string;
  pathname?: string;
  noIndex?: boolean;
  children?: React.ReactNode;
};

const Seo: React.FC<SeoProps> = ({ lang, title, description, pathname, noIndex, children }) => {
  const { siteTitle, siteDescription, siteSocial, siteAuthor } = useSiteMetadata();

  const metaDescription = description || siteDescription;
  const metaTitle = title ? `${title} | ${siteTitle}` : `${siteTitle} | ${siteAuthor.jobTitle}`;
  const twitterHandle = siteSocial.find(({ name }) => name === 'Twitter')?.url ?? '';
  const canonicalUrl = pathname ? `${SITE_METADATA.url}${pathname}` : SITE_METADATA.url;
  // Largest icon generated by gatsby-plugin-manifest, served from a stable path.
  const ogImage = `${SITE_METADATA.url}/icons/icon-512x512.png`;

  return (
    <>
      <html lang={lang ?? SITE_METADATA.lang} />
      <title>{metaTitle}</title>
      <meta name="description" content={metaDescription} />

      <meta property="og:title" content={metaTitle} />
      <meta property="og:description" content={metaDescription} />
      <meta property="og:type" content="website" />
      <meta property="og:url" content={canonicalUrl} />
      <meta property="og:image" content={ogImage} />

      <meta name="twitter:card" content="summary" />
      <meta name="twitter:creator" content={twitterHandle} />
      <meta name="twitter:title" content={metaTitle} />
      <meta name="twitter:description" content={metaDescription} />
      <meta name="twitter:image" content={ogImage} />

      {noIndex && <meta name="robots" content="noindex, nofollow" />}

      {children}
    </>
  );
};

export default Seo;
