name: Continuous Integration

on:
  pull_request:

concurrency:
  group: 'ci-${{ github.event.pull_request.number }}'
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check: ['type:check', 'format:check']
        node: ['22']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run Check
        run: pnpm run ${{ matrix.check }}

      - name: Run build
        run: pnpm run build
